services:
  bind9:
    container_name: bind9
    image: internetsystemsconsortium/bind9:9.18
    restart: always
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 127.0.0.1:953:953/tcp
  mongodb:
    container_name: mongodb
    image: mongo:7.0.14-jammy
    restart: always
    environment:
      - MONGODB_INITSCRIPTS_DIR=/docker-entrypoint-initdb.d
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_DATABASETWO=${MONGO_INITDB_DATABASETWO}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    ports:
      - "27017:27017"
    volumes:
      - /mnt/docker.mongo:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DBNAME=${MONGO_INITDB_DATABASE}
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=8192 #optional
      - MEM_STARTUP=4096 #optional
      - MONGO_TLS= #optional
    volumes:
      - /mnt/docker.unifi/data:/config
    links:
      - mongodb
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
